language: node_js
node_js:
- 6.3.1
before_install:
- openssl aes-256-cbc -K $encrypted_6e6c7b3070ed_key -iv $encrypted_6e6c7b3070ed_iv
  -in stack-images.enc -out stack-images -d
- gem update --system
- gem install sass normalize-scss
- npm install -g bower@1.7.9 grunt-cli@1.2.0
script:
- bash ./deploy.sh
